### ISSUE TITLE
Delete message verification

### ISSUE THREAD

**Issue by marcianovc** [ejnshtein/antibot#2]
Is it possible for the bot to delete the verification message after banning the unchecked user?

**Comment by ejnshtein** [comment]
Sure.
I just pushed an update.
Idk why these messages weren't deleted, because I store them in DB, and call API to delete then when ban bots.

**Comment by ejnshtein** [comment]
![image](https://user-images.githubusercontent.com/18352350/53198317-cc8c9a80-3624-11e9-9a0e-cce701e15976.png)
Yay, it works.

You can close the issue, if you want

**Comment by marcianovc** [comment]
> ![image](https://user-images.githubusercontent.com/18352350/53198317-cc8c9a80-3624-11e9-9a0e-cce701e15976.png)
> Yay, it works.
> 
> You can close the issue, if you want

here is not yet working, the bot bans the user but the captcha messages are still in the group

**Comment by ejnshtein** [comment]
idk, it's deleting it from my groups.

**Comment by marcianovc** [comment]
ok
